import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import java.security.MessageDigest

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidKmpLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

kotlin {
    android {
        namespace = "com.reelscout.app.ui"
        compileSdk = 37
        minSdk = 26

        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    jvm("desktop")

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { target: KotlinNativeTarget ->
        target.binaries.framework {
            baseName = "composeApp"
            isStatic = true
        }
    }

    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName.set("reelscout")
        browser {
            commonWebpackConfig {
                outputFileName = "reelscout.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        val desktopMain = getByName("desktopMain")

        commonMain.dependencies {
            implementation(project(":shared"))

            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.components.ui.tooling.preview)
            implementation(libs.markdown.renderer.m3)
            implementation(libs.multiplatform.settings.no.arg)
            implementation(libs.kotlinx.serialization.json)

            implementation(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.runtime.compose)

            implementation(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)
        }

        androidMain.dependencies {
            implementation(libs.compose.ui.tooling)
            implementation(libs.ktor.client.okhttp)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }

        desktopMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.ktor.client.cio)
            implementation(libs.kotlinx.coroutines.core)
            // Provides Dispatchers.Main on desktop - viewModelScope launches on it.
            implementation(libs.kotlinx.coroutines.swing)
        }

        wasmJsMain.dependencies {
            implementation(libs.ktor.client.js)
        }
    }
}

// reelscout.js keeps the same name in every build, and the Cloudflare zone lets browsers
// cache .js for 4 hours, so visitors kept running the previous build after a deploy.
// index.html (never cached) loads it as reelscout.js?v=<content hash> instead: a new build
// gets a new URL, and an unchanged one keeps its cache.
val wasmDistDir = layout.buildDirectory.dir("dist/wasmJs/productionExecutable")
tasks.named("wasmJsBrowserDistribution") {
    doLast {
        val dir = wasmDistDir.get().asFile
        val version = MessageDigest.getInstance("SHA-256")
            .digest(dir.resolve("reelscout.js").readBytes())
            .joinToString("") { "%02x".format(it) }
            .take(12)
        val index = dir.resolve("index.html")
        val html = index.readText()
        check("src=\"reelscout.js\"" in html) { "index.html no longer loads reelscout.js - update this step" }
        index.writeText(html.replace("src=\"reelscout.js\"", "src=\"reelscout.js?v=$version\""))
    }
}

compose.desktop {
    application {
        mainClass = "com.reelscout.app.MainKt"
        nativeDistributions {
            targetFormats(
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Dmg,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Msi,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Deb
            )
            packageName = "ReelScout"
            packageVersion = "0.1.0"

            // Generated by branding/generate_icons.py.
            // packageName stays one word: it names the installer files, and Linux .deb
            // package names can't contain spaces. The Dock shows the display name.
            macOS {
                iconFile.set(project.file("icons/icon.icns"))
                dockName = "Reel Scout"
            }
            windows { iconFile.set(project.file("icons/icon.ico")) }
            linux { iconFile.set(project.file("icons/icon.png")) }
        }
    }
}
